services:
    look_for_tweet_use_case:
        class: SocialDataPool\Application\Service\Core\WithEventHandling
        arguments:
            - "@look_for_tweet_use_case_original"
            - "@sqs_php.client"
    look_for_tweet_use_case_original:
        class: SocialDataPool\Application\Service\Tweet\LookForTweet
        public: false
        arguments:
            - "@twitter_api_client"
            - "@tweet_processor"
    tweet_processor:
        class: SocialDataPool\Domain\Service\TweetProcessor
        arguments:
            - "@tweet_writer"
    tweet_writer:
        class: SocialDataPool\Infrastructure\Repository\Twitter\RedisTweetWriter
        arguments:
            - "@redis_client"
    tweet_reader:
        class: SocialDataPool\Infrastructure\Repository\Twitter\RedisTweetReader
        arguments:
            - "@redis_client"
    redis_client:
        class: SocialDataPool\Infrastructure\Redis\RedisClient
        arguments:
            - "@predis"
    predis:
        class: Predis\Client
        public: false
        arguments:
            - "%redis_parameters%"
