parameters:
    redis_host: 127.0.0.1
    redis_port: 6378

services:
    redis_client:
        class: SocialDataPool\Infrastructure\RedisClient
        arguments:
            - "@predis"
    predis:
        class: Predis\Client
        arguments:
            host: %redis_host%
            port: %redis_port%
