parameters:
    redis_parameters:
        scheme:
            - tcp
        host:
            - 127.0.0.1
        psot:
            - 6378
services:
    tweet_repository:
        class: SocialDataPool\Infrastructure\Repository\Twitter\TweetRepository
        arguments:
            - "@redis_client"
    redis_client:
        class: SocialDataPool\Infrastructure\Redis\RedisClient
        arguments:
            - "@predis"
    predis:
        class: Predis\Client
        arguments:
            - redis_parameters
