services:
    get_top_selling_products_use_case:
        class: SocialDataPool\Application\Service\Uvinum\GetTopSellingProducts
        arguments:
            - "@uvinum_api_client"
    look_for_instagram_post_use_case:
        class: SocialDataPool\Application\Service\Core\WithEventHandling
        arguments:
            - "@look_for_instagram_post_use_case_original"
            - "@sqs_php.client"
    look_for_instagram_post_use_case_original:
        class: SocialDataPool\Application\Service\Instagram\LookForInstagramPost
        arguments:
            - "@instagram_api_client"
            - "@uvinum_api_client"
            - "@instagram_processor"
    instagram_processor:
        class: SocialDataPool\Domain\Service\Instagram\InstagramPostProcessor
        arguments:
            - "@instagram_writer"
            - "@instagram_reader"
            - "@instagram_json_adapter"
    instagram_json_adapter:
        class: SocialDataPool\Infrastructure\Service\Adapter\Instagram\JsonAdapter
    instagram_writer:
        class: SocialDataPool\Infrastructure\Repository\Instagram\RedisInstagramWriter
        arguments:
            - "@redis_client"
    instagram_reader:
        class: SocialDataPool\Infrastructure\Repository\Instagram\RedisInstagramReader
        arguments:
            - "@redis_client"
    look_for_tweet_use_case:
        class: SocialDataPool\Application\Service\Core\WithEventHandling
        arguments:
            - "@look_for_tweet_use_case_original"
            - "@sqs_php.client"
    look_for_tweet_use_case_original:
        class: SocialDataPool\Application\Service\Tweet\LookForTweet
        public: false
        arguments:
            - "@twitter_api_client"
            - "@uvinum_api_client"
            - "@tweet_processor"
    tweet_processor:
        class: SocialDataPool\Domain\Service\Twitter\TweetProcessor
        arguments:
            - "@tweet_writer"
            - "@tweet_reader"
            - "@twitter_json_adapter"
    twitter_json_adapter:
        class: SocialDataPool\Infrastructure\Service\Adapter\Twitter\JsonAdapter
    tweet_writer:
        class: SocialDataPool\Infrastructure\Repository\Twitter\RedisTweetWriter
        arguments:
            - "@redis_client"
    tweet_reader:
        class: SocialDataPool\Infrastructure\Repository\Twitter\RedisTweetReader
        arguments:
            - "@redis_client"
    redis_client:
        class: SocialDataPool\Infrastructure\Redis\RedisClient
        arguments:
            - "@predis"
    predis:
        class: Predis\Client
        public: false
        arguments:
            - "%redis_parameters%"
    instagram_authentication_controller:
        class: SocialDataPoolBundle\Bundle\Controller\InstagramAuthenticationController
    instagram_api_client:
        class: SocialDataPool\Infrastructure\Api\Instagram\InstagramApiClient
        arguments:
            - "%instagram_client_id%"
            - "%instagram_client_secret%"
            - "http://ubuntu.dev/winegram_social_data_pool/web/app_dev.php/instagram/code"
    uvinum_api_client:
        class: SocialDataPool\Infrastructure\Api\Uvinum\UvinumApiClient
        arguments:
            - "%uvinum_api_key%"
